DW\PortfolioBundle\Entity\Enquiry:
    properties:
        name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: durrrrr
        telephone: ~
        message:
            - NotBlank: ~